# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMOJ1XpPdVGjetl_PeyVpX2smdvqPGpR
"""

def kasallik_tashxisi(belgi):
  if belgi == "Istima":
   return "Parasetamol iching"
  elif belgi == "Bosh og'rig'i":
   return "Bolnol"
  elif belgi == "Tish og'rig'i":
   return "Senapar"
  elif belgi == "Qorin og'rig'i":
   return "Bobotik"
  elif belgi == "Shamollash":
   return "Taylol hot"
  elif belgi == "Bo'g'im og'rig'i":
   return "Zefam"
  elif belgi == "Tumov":
   return "Renoksin"
  elif belgi == "Lat yeyish":
   return "Yotsurtish"
  elif belgi == "Toshma toshishi":
   return "Sinaflan"
  elif belgi == "Ko'z og'rig'i":
   return "Lutax"
  else :
   return "Shifokorga murojat qiling"
belgi=input("Kasallik belgisini kiriting ")
natija=kasallik_tashxisi(belgi)
print(natija)